In [34]:
# SA1
def prefix_sum(arr):
    for i in range(1,len(arr)):
        arr[i] += arr[i-1]
    return arr
a = [1,3,5,7,2,4,6,8]
print(prefix_sum(a))

[1, 4, 9, 16, 18, 22, 28, 36]


In [35]:
# SA2
[(i,i*i) for i in range(5)]

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16)]

In [36]:
# SA3
# a n
# b nlog(n)

In [38]:
# SA4
def upique_and_sorted(s):
    d = {}
    for i in s:
        if i not in d:
            d[i]=0
    res = list(d.keys())
    res.sort()
    return res
upique_and_sorted([1,3,5,3,4,6,7,8,2,3,4])

[1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
# SA5
def dict1(func):
    D = {0:0,1:1,2:2}
    def _decorator(param):
        if param in D:
            return D[param]
        else:
            D[param] = _decorator(param-1) + _decorator(param - 2) + _decorator(param//2)
            return D[param]
    return _decorator    
@dict1
def f(n):
    if n ==0:
        return 0
    elif n == 1:
        return 1
    elif n == 2:
        return 2
    else:
        return f(n-1) + f(n-2)+f(n//2)
print(f(14))
print(f(200))

1664
1317261742621463123234288924400109075146188


In [52]:
# SA6
# He ended his speech saying 'Your team completed the project beautifully'
def q6():
    temp = input("Enter a sentence: ")
    L = temp.split(" ")
    res = []
    for i in L:
        if i[-2:] == "ed":
            res.append(i)
    print("The word ended with ed are here")
    for ele in res:
        print(ele)
q6()

Enter a sentence: He ended his speech saying 'Your team completed the project beautifully'
The word ended with ed are here
ended
completed


In [59]:
# SA7
print("The 2 by 3 array is ")
res = np.array([2**i for i in range(6)]).reshape(2,3)
print(res)
print("The flatten array is")
print(res.reshape(-1))

The 2 by 3 array is 
[[ 1  2  4]
 [ 8 16 32]]
The flatten array is
[ 1  2  4  8 16 32]


In [1]:
def q8(sentence):
    L = sentence.split(" ")
    res = {}
    for i in L:
        i = i.lower()
        if i in res:
            res[i] +=1
        else:
            res[i] = 1
    print("WORD\t\tCOUNT")
    for key,value in res.items():
        if value >=2:
            print(key,"\t\t",value)
q8("this is sample text with several words this is more sample text with some different words")

WORD		COUNT
this 		 2
is 		 2
sample 		 2
text 		 2
with 		 2
words 		 2
